name: fz_copy_ensure_visible
description: Ensure visible when focused widget (copied from Flutter).
publish_to: 'none'
version: 0.1.0
environment:
  sdk: "^3.9.0"
dependencies:
  flutter:
    sdk: flutter

dependency_overrides:
  intl: ^0.20.2
  archive: ^4.0.7
