name: fz_future_handling
description: Future handling widgets and utilities for FromZero UI.
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.3.1
  dartx: ^1.2.0

  fz_animated_switcher_image:
    path: ../fz_animated_switcher_image
  fz_animations:
    path: ../fz_animations
  fz_dialog:
    path: ../fz_dialog
  fz_export:
    path: ../fz_export
  fz_localizations:
    path: ../fz_localizations
  fz_opacity_gradient:
    path: ../fz_opacity_gradient
  fz_scrollbar:
    path: ../fz_scrollbar
  fz_ui_utility:
    path: ../fz_ui_utility

dev_dependencies:
  flutter_lints: ^5.0.0
