name: fz_combo
description: Combo (dropdown/combobox) widget for FromZero UI.
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^3.3.1

  fz_dao:
    path: ../fz_dao
  fz_flutter_riverpod:
    path: ../fz_flutter_riverpod
  fz_future_handling:
    path: ../fz_future_handling
  fz_localizations:
    path: ../fz_localizations
  fz_popup:
    path: ../fz_popup
  fz_riverpod:
    path: ../fz_riverpod
  fz_scrollbar:
    path: ../fz_scrollbar
  fz_table:
    path: ../fz_table
  fz_tooltip:
    path: ../fz_tooltip
  fz_ui_utility:
    path: ../fz_ui_utility

dev_dependencies:
  flutter_lints: ^5.0.0
