name: fz_drawer_menu
description: Responsive drawer menu for FromZero UI.
publish_to: 'none'
version: 0.1.0
environment:
  sdk: "^3.9.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.0.0-dev.9
  dartx: ^1.2.0
  go_router: 10.0.0

  fz_actions:
    path: ../fz_actions
  fz_copy_tooltip:
    path: ../fz_copy_tooltip
  fz_expansion_tile:
    path: ../fz_expansion_tile
  fz_popup:
    path: ../fz_popup
  fz_router:
    path: ../fz_router
  fz_scaffold:
    path: ../fz_scaffold
  fz_scrollbar:
    path: ../fz_scrollbar
  fz_ui_utility:
    path: ../fz_ui_utility

dependency_overrides:
  intl: ^0.20.2
  archive: ^4.0.7
