name: fz_number_format
description: Extended number formatting utilities for Flutter.
publish_to: 'none'
version: 0.1.0
environment:
  sdk: "^3.9.0"
dependencies:
  intl: ^0.20.2

dependency_overrides:
  intl: ^0.20.2
  archive: ^4.0.7

dev_dependencies:
  lints: ^5.0.0
