name: fz_number_format
description: Extended number formatting utilities for Flutter.
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  intl: ^0.20.2

dev_dependencies:
  lints: ^5.0.0
