name: fz_web_platform_impl
description: Web platform implementation utility for Flutter.
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: "^3.9.0"

dependencies:
  flutter:
    sdk: flutter

  platform_detect: ^2.0.7

dev_dependencies:
  flutter_lints: ^5.0.0
