name: fz_tooltip
description: Material tooltip widget (copied and customized from Flutter).
publish_to: 'none'
version: 0.1.0
environment:
  sdk: "^3.9.0"
dependencies:
  flutter:
    sdk: flutter
  fz_platform:
    path: ../fz_platform
  fz_scrollbar:
    path: ../fz_scrollbar

dependency_overrides:
  intl: ^0.20.2
  archive: ^4.0.7
