name: fz_popup
description: Popup and context menu widgets for FromZero UI.
publish_to: 'none'
version: 0.1.0
environment:
  sdk: "^3.9.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.0.0-dev.9
  dartx: ^1.2.0

  fz_actions:
    path: ../fz_actions
  fz_platform:
    path: ../fz_platform
  fz_scaffold:
    path: ../fz_scaffold
  fz_scrollbar:
    path: ../fz_scrollbar
  fz_snackbar:
    path: ../fz_snackbar

dependency_overrides:
  intl: ^0.20.2
  archive: ^4.0.7

dev_dependencies:
  flutter_lints: ^5.0.0
